### ISSUE TITLE
..helpers/extractors not found

### ISSUE THREAD

**Issue by Boy19991** [muhamed-didovic/vmdown#1]
Bro, looks like greats software however 

https://github.com/muhamed-didovic/vmdown/search?q=helpers%2Fextractors

these files cannot be found?

What should we do?

Nick.

**Comment by muhamed-didovic** [comment]
Hi @Boy19991, pull new version and let me know :)

**Comment by Boy19991** [comment]
Thanks for the quick update.

Error thrown Error: no chrome installations found

Do I need to Chrome install to run this app?

**Comment by muhamed-didovic** [comment]
did you run 'npm i'?
'npm i' should install chrome version for you, which option did you choose for download?

**Comment by Boy19991** [comment]
yes, I ran npm i (inside the vmdown folder)
what should I check for in node_modules?

one more thing,
three or four times "module not found" occurred, and I manually npm i __module_name__ to get past it.
one of those was youtube-dl-wrap

everything in package.json seems to be inside node_modules

thanks for quick reply, was very nice

**Comment by Boy19991** [comment]
some results from the terminal  

```
downDir: '/home/flesh/Desktop/vmdown/vmdown',
  videos: true,
  markdown: true,
  images: true,
  concurrency: 10,
  extension: '.mp4',
  quality: '1080p',
  pdf: true,
  framework: 'p',
  overwrite: 'no'
}
Courses found: 1
Error thrown Error: no chrome installations found
    at Object.<anonymous> (/home/flesh/Desktop/vmdown/vmdown/node_modules/chrome-finder/lib/index.js:3:38)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/flesh/Desktop/vmdown/vmdown/api/puppeteer/helpers.js:3:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)

```

**Comment by muhamed-didovic** [comment]
nice, you should have this dependency in your package.json: "chrome-finder": "^1.0.7", 
which downloads chrome for you?

**Comment by muhamed-didovic** [comment]
also if you have any other issues or something please let me know, especially during installation of the project

**Comment by Boy19991** [comment]
I would love to get this working, I don't like watching videos online.

Are you doing any language/dictionary related projects? What languages do you speak?

Rikaikun is a Japanese-English in-browser popup dictionary (invaluable), worth a look.

**Comment by muhamed-didovic** [comment]
find on me on linkedin, let's continue there?

**Comment by Boy19991** [comment]
Im not on linkedin, sorry I talk too much.
You must speak some Russian though?
Slava Dictionary plugin for brave...

**Comment by muhamed-didovic** [comment]
sorry, I don't speak Russian, so were you able to install and start downloader?

**Comment by Boy19991** [comment]
```
nvm use 18
Now using node v18.11.0 (npm v8.19.2)
node index.js
```
this get the prompt started, until the error I showed you above occurs

also,
```
npx vmdown
/home/flesh/Desktop/vmdown/node_modules/.bin/vmdown: 1: Syntax error: "(" unexpected
```

does this give you any clues?

**Comment by muhamed-didovic** [comment]
what if you run 'node index.js' when you pull the project and run it inside the project?

**Comment by Boy19991** [comment]
starting fresh

```
git clone git@github.com:muhamed-didovic/vmdown.git
cd vmdown
nvm use 18 (neccessary?)
npm i
node index.js
```

Does this look right?

update:
following these steps I get the same 
`Error thrown Error: no chrome installations found
    at Object.<anonymous> (/home/flesh/Desktop/vmdown/vmdown/node_modules/chrome-finder/lib/index.js:3:38)`

**Comment by muhamed-didovic** [comment]
please check this and let me know: https://github.com/gwuhaolin/chrome-finder

**Comment by muhamed-didovic** [comment]
hey @Boy19991, I made some changes, please pull the new version and try again like you used to do and let me know if it works for you

**Comment by Boy19991** [comment]
```
Courses found: 6
Checking authentication...
logged text: Login
Logged: false Login
User successfully logged in.
error-- Error: turing... 6 of 6 https://www.vuemastery.com/courses/from-vue2-
Error code: -2new-attrs/
Process error:
Error: spawn youtube-dl ENOENT
    at YoutubeDlWrap.createError (/home/flesh/Desktop/sarajavo/v2/vmdown/node_modules/youtube-dl-wrap/index.js:230:10)
    at ChildProcess.<anonymous> (/home/flesh/Desktop/sarajavo/v2/vmdown/node_modules/youtube-dl-wrap/index.js:109:62
```

damn. Just cant get it working.

By the way you need to install Chrome separately for chrome-finder to work.

Thanks for all your hard work.

**Comment by muhamed-didovic** [comment]
we are getting closer :), 
please verify that youtube-dl is installed on your system(also what do you use as OS) , you can check in terminal with 'youtube-dl -v'

**Comment by Boy19991** [comment]
```
Courses found: 11
Checking authentication...
logged text: Login
Logged: false Login
User successfully logged in.
error-- Error: turing... 7 of 11 https://www.vuemastery.com/courses/intro-to-
Error code: -2omputed-properties/

Process error:
Error: spawn youtube-dl ENOENT
    at YoutubeDlWrap.createError (/home/flesh/Desktop/sarajavo/v2/vmdown/node_modules/youtube-dl-wrap/index.js:230:10)
    at ChildProcess.<anonymous> (/home/flesh/Desktop/sarajavo/v2/vmdown/node_modules/youtube-dl-wrap/index.js:109:62)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
.... retrying left (6)
retrying err Error: 
Error code: -2

Process error:
Error: spawn youtube-dl ENOENT
    at YoutubeDlWrap.createError (/home/flesh/Desktop/sarajavo/v2/vmdown/node_modules/youtube-dl-wrap/index.js:230:10)
    at ChildProcess.<anonymous> (/home/flesh/Desktop/sarajavo/v2/vmdown/node_modules/youtube-dl-wrap/index.js:109:62)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
⠏ Puppeteer Capturing... 7 of 11 https://www.vuemastery.com/courses/intro-to-
  vue-js/vue-computed-properties/
/home/flesh/Desktop/sarajavo/v2/vmdown/node_modules/dreidels/index.js:436
    if (!this.spinners[name]) throw new Error(`No spinner initialized with name ${name}`);
                              ^

Error: No spinner initialized with name /home/flesh/Desktop/sarajavo/v2/vmdown/videos/intro-to-vue-js/1. The Vue Instance.mp40
```

```
npm youtube-dl-wrap --version
8.19.2
npm youtube-dl --version
8.19.2
```

these are all installed locally, not globally.

Above,  maybe this is the problem
 **if (!this.spinners[name]) throw new Error(`No spinner initialized with name ${name}`);**

using Ubuntu 22.04

Maybe I should be using Yarn? I heard npm gives different results across different machines.

Thanks for all your work.

**Comment by muhamed-didovic** [comment]
hey, please write in terminal 'youtube-dl -v' and let's see what you get?

**Comment by Boy19991** [comment]
Bro, I installed youtube-dl globally (everything else locally within vmdown folder) and it works.

Legendary software.

So much better than watching online.

**Comment by muhamed-didovic** [comment]
so it works, sounds great :)
Can you tell me what can be improved regarding the installation and easy of use?
