### ISSUE TITLE
Error: spawn yt-dlp ENOENT

### ISSUE THREAD

**Issue by zappzerapp** [muhamed-didovic/vmdown#3]
Hi,

I'm running the latest version on Ubuntu 22 with Node 18 + npm 9.5.1
Unfortunately I get the following error code:

```
Error code: -2

Process error:
Error: spawn yt-dlp ENOENT
    at YTDlpWrap.createError (/usr/local/lib/node_modules/vmdown/node_modules/yt-dlp-wrap/dist/index.js:347:16)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/vmdown/node_modules/yt-dlp-wrap/dist/index.js:174:58)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)
------> tu smo
```

**Comment by muhamed-didovic** [comment]
@zappzerapp I think it is related to yt-dlp, but let me see how it goes on my end

**Comment by muhamed-didovic** [comment]
@zappzerapp pushed new version...

**Comment by aynaitlamine** [comment]
I had the same Issue but I fix it by installing yt-dlp from github  

`sudo wget -qO /usr/bin/yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp`

`sudo chmod a+rx /usr/bin/yt-dlp`

`yt-dlp --version`

and then update it 

`sudo yt-dlp -U`

**Comment by zappzerapp** [comment]
Thank you!
